version: '3.8'

services:
  # MongoDB database
  mongodb:
    image: mongo:5.0
    container_name: meetingapp-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - meetingapp-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: meetingapp-backend
    restart: always
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://admin:password@mongodb:27017/meetingapp?authSource=admin
      - JWT_SECRET=your_jwt_secret_here
      - JWT_EXPIRE=7d
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - meetingapp-network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: meetingapp-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - meetingapp-network

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: meetingapp-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - meetingapp-network

volumes:
  mongodb_data:

networks:
  meetingapp-network:
    driver: bridge